login/urls.py
from django.urls import path

from . import views

app_name = 'system'

urlpatterns = [
    path('login/', views.login_template, name='login'),
    path('register/', views.register_template, name='register'),
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout_template, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


def login_template(request):
    if request.method == 'GET':
        return render(request, 'login/pages/login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return render(request, 'login/pages/index.html')
        messages.error(request, 'User/password is invalid or does not exist')
        return render(request, 'login/pages/login.html')


def logout_template(request):
    logout(request)
    return login_template(request)


def register_template(request):
    if request.method == 'GET':
        return render(request, 'login/pages/register.html')
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        re_password = request.POST.get('re_password')

        user = User.objects.filter(username=username).first()
        password_bool = password != re_password
        is_empty = (username == '' or email == ''
                    or password == '' or re_password == '')
        if user:
            messages.error(request, 'User already exist')
            return render(request, 'login/pages/register.html')
        elif password_bool:
            messages.warning(request, 'Passwords are not equal')
            return render(request, 'login/pages/register.html')
        elif is_empty:
            messages.warning(request, 'Fulfill all the informations')
            return render(request, 'login/pages/register.html')
        user = User.objects.create_user(
            username=username, email=email, password=password)
        user.save()
        messages.success(request, 'Registration complete sucessfuly')
        return render(request, 'login/pages/register.html')


def index(request):
    return render(request, 'login/pages/index.html')


@login_required(login_url='system:login')
def home(request):
    return render(request, 'login/pages/home.html')

login/templates/login/pages/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <main class="main-container">

    {% block buttons %}
            <div class="back">
                <h1><a href="{% url 'system:index' %}">↩</a></h1><p>Back</p>
            </div>
            {% if user.is_authenticated %}
                <div class="logout">
                    <h3><a href="{% url 'system:logout' %}">Logout</a></h3>
                </div>
            {% endif %}
    {% endblock buttons %}
    <div class="form-container">  

        {% if messages %}
        <div class="alert-container">
            {% for msg in messages %}
                <div class="messages {{ msg.tags }}">
                {{msg}}
            {% endfor %}
            </div>
        </div>
        {% endif %}  

    <form action="." method="POST">
        {% csrf_token %}
        {% block form %}
        <h1>This is the plataform after log</h1>
        {% endblock form %}
        {% block auxiliar %}
        {% endblock auxiliar %}
    </form>
    </main>
</body>
</html>

login/templates/login/pages/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
    <title>Home</title>
</head>
<body>
    {% block buttons %}
        <main class="main-container">
        
            {% if request.user.is_authenticated %}
                <div class="logout">
                    <h3><a href="{% url 'system:logout' %}">Logout</a></h3>
                </div>   
            {% endif %}
    {% endblock buttons %}
        <div class="container-options">
            <div class="options">
                <h2><a href="{% url 'system:login' %}">Login</a></h2>
                <h2><a href="{% url 'system:register' %}">Register</a></h2>
                <h2><a href="{% url 'system:home' %}">Home</a></h2>
            </div>
        </div>
    </main>
</body>
</html>

login/templates/login/pages/login.html
{% extends 'login/pages/home.html' %}

{% block title %}Login{% endblock title %}

{% block buttons %}
        <div class="back">
            <h1><a href=" {% url 'system:index' %} ">↩</a></h1>
        </div>
{% endblock buttons %}
{% block form %}
<label for="username">Username</label>
<input type="text" name='username' placeholder='username'>

<label for="password">Password</label>
<input type="password" name='password' placeholder='password'>
<button id = "btn" class="btn" type="submit">Login</button>

{% endblock form %}
{% block auxiliar %}
        <div class="auxiliar-login">
            <a href="{% url 'system:register' %}">
                <p>Create account</p>
            </a>
        </div> 
{% endblock auxiliar %}

login/templates/login/pages/register.html
{% extends 'login/pages/home.html' %}

{% block title %}Cadastro{% endblock title %}
{% block buttons %}
    <div class="back">
        <h1><a href="{% url 'system:index' %}">↩</a></h1><p>Back</p>
    </div>
{% endblock buttons %}
{% block form %}
    <label for="username">Username</label>
    <input type="text" name='username' placeholder='username'>

    <label for="email">E-mail</label>
    <input type="email" name='email' placeholder='email'>

    <label for="password">Password</label>
    <input type="password" name='password' placeholder='password'>

    <label for="re_password">Your password again</label>
    <input type="password" name='re_password' placeholder='Type your password again'>
    <button id = "btn" class="btn" type="submit">Save</button>

{% endblock form %}